---
# tasks file for deploy_legacy_app
- name: Ensure namespace exists
  k8s:
    kind: Namespace
    api_version: v1
    name: "{{ deploy_legacy_app_namespace }}"
    state: present

- name: Deploy the app
  k8s:
    namespace: test
    definition: "{{ lookup('template', 'app.yml.j2') | from_yaml }}"